version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./Server/Dockerfile.local
    image: food-ordering-server-local
    depends_on:
      - logichandler
  logichandler:
    build:
      context: .
      dockerfile: ./LogicHandler/Dockerfile.local
    image: food-ordering-logichandler-local
    depends_on:
      - rabbit
  dbmigrator:
    build:
      context: .
      dockerfile: ./Migrator/Dockerfile.local
    image: food-ordering-migrator
    environment:
      - DOTNET_ENVIRONMENT="Production"
    depends_on:
      - rabbit
      - db
    networks:
      - api
  rabbit:
    restart: on-failure
    image: rabbitmq:management
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
      - api
  db:
    image: postgres
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  rabbit-data:
  db-data:
