version: "3"

services:
  server:
    build:
      - dockerfile:  ./Server/Dockerfile.local
    image: food-ordering-server-local
    depends_on:
      - backend
  backend:
    build:
      - dockerfile:  ./Backend/Dockerfile.local
    image: food-ordering-backend-local
    depends_on:
      - rabbit
  rabbit:
    restart: on-failure
    image: rabbitmq:management
    volumes:
    - rabbit-data:/var/lib/rabbitmq
    networks:
      - api
  db:
    image: postgres
    restart: on-failure
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbpassword
    ports:
    - "5432:5432"
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  rabbit-data:
  db-data:
